### PR TITLE
Update usage of Env.exitcode to be compatible with ponyc 0.22.x

### PR DESCRIPTION
**Pull request by jemc**
After merging https://github.com/ponylang/ponyc/pull/2617 to ponyc, pony-stable needs this update to be compatible with latest ponyc master.

### CODE REVIEW

**Review by chalcolith — APPROVED** [review]

**Comment by jemc** [comment]
I notice that this breaks the CI build - what do we want to do about that? Wait until the release of next ponyc to merge this?

**Comment by SeanTAllen** [comment]
I think so

**Review by EpicEric — APPROVED** [review]

**Comment by SeanTAllen** [comment]
@jemc can you rebase this against master AND switch circle-ci to using "latest" for ci purposes for now? once that passes and 0.22.0 comes out we can update this again to be back on "ponyc-release", watch ci pass and merge to master.

**Comment by SeanTAllen** [comment]
Actually @jemc, if you rebase this against master now that 0.22.1 is out, we should be good.

**Comment by SeanTAllen** [comment]
@jemc realized i can rebase this against master. did. running tests.

**Comment by SeanTAllen** [comment]
Passed!

**Pull request merged**
