### PR TITLE
Update Windows build to use 'build/release' and 'build/debug' directories

### PR DESCRIPTION
**Pull request by chalcolith**
Changed the `make.bat` file to allow the following:

```
make                # builds release in build/release
make config=release # builds release in build/release
make config=debug   # builds debug in build/debug
make clean          # deletes build/
```

### CODE REVIEW

**Comment by SeanTAllen** [comment]
That `make clean` is different than what the "unix" version does. The gnu makefile does the same thing as the ponyc gnu makefile. if you run make clean then that defaults to config=release and only removed `build/release`

**Comment by chalcolith** [comment]
Ok, now `make clean` will clean `build/release` and `make clean config=debug` will clean `build/debug`.

**Comment by SeanTAllen** [comment]
@kulibali `make clean config=release` does the same as `make clean` yes?

**Comment by chalcolith** [comment]
Yes.

**Pull request merged**
