### PR TITLE
Resolve Local Dependencies From Bundle Path

### LINKED ISSUE #22: Local dependencies are relative to invocation directory, not `bundle.json`
```
/> tree
.
├── pony-bar
│   ├── bar
│   │   └── bar.pony
│   └── bundle.json
└── pony-foo
    └── foo
        └── foo.pony
/> cd pony-bar
/pony-bar> stable add local ../pony-foo
/pony-bar> cd bar
/pony-bar/bar> stable env ponyc -d
Building builtin -> /usr/local/Cellar/ponyc/0.15.0/packages/builtin
Building . -> /pony-bar/bar
Error:
foo: couldn't locate this path
Error:
/pony-bar/bar/bar.pony:1:1: can't load package 'foo'
use "foo"
^
```
Because I'm in the `/pony-bar/bar` folder, the `../pony-foo` path refers to `/pony-bar/pony-foo`, which obviously doesn't exist. This seems unintuitive to me. I would expect all paths to be relative to the `bundle.json` file.

This probably affects `local-git` dependencies as well.

### PR DESCRIPTION
**Pull request by rawkode**
Fixes #22

### CODE REVIEW

**Comment by SeanTAllen** [comment]
@rawkode looks like there is a test failure.

**Comment by rawkode** [comment]
Hi @SeanTAllen,

This should build successfully now. One thing I'd appreciate some guidance on though:

The following works, without error:

```pony
Path.join(tmp.path, "../local/a") + ":" +
```

but the following fails:

```pony
tmp.join("../local/a")?.path
```

Which I find strange, as the following works:

```pony
```pony
tmp.join("./local/a")?.path
```

I don't understand why :confused:

Is this a bug in the `join` code, perhaps?

**Comment by SeanTAllen** [comment]
`Path.join` is building a path from a string (tmp.path)

`tmp` was probably created with `FilePath` capability which doesn't allow you to use it to access directories above that level. See `create` inside of `FilePath` which gets called by your `tmp.join`.

```pony
    path = match base
      | let b: FilePath =>
        if not b.caps(FileLookup) then
          error
        end

        let tmp_path = Path.join(b.path, path')
        caps.intersect(b.caps)

        if not tmp_path.at(b.path, 0) then
          error
        end
        tmp_path
      | let b: AmbientAuth =>
        Path.abs(path')
      end
```

**Comment by rawkode** [comment]
@SeanTAllen I believe this PR is good to go, regardless of my question (Hopefully :+1: )

**Comment by SeanTAllen** [comment]
Before this is merged, we need a good release message for this as it is a breaking change.

@rawkode do you feel up to writing that? If yes, have a go and put it in a comment here. Ideally, we'd want an explanation of what changed, why, and before and after examples of what what one would need to change (if applicable).

**Review by SeanTAllen — APPROVED** [review]

**Comment by rawkode** [comment]
Resolve Local Dependencies From Bundle Path

Previously, if a `stable` command was executed deeper in the directory hierarchy than the `bundle.json` files, relative dependencies would be resolved from where the command was executed. 

Now, all relative dependencies are resolved relatively from the `bundle.json` directory.

This resolution is more intuitive and predictable.

**Comment by rawkode** [comment]
`SYN`

**Comment by SeanTAllen** [comment]
Thanks @rawkode

**Pull request merged**
