### PR TITLE
Switch nightly build to using a statically linked stable

### PR DESCRIPTION
**Pull request by SeanTAllen**

### CODE REVIEW

**Comment by SeanTAllen** [comment]
@dipinhora what do i want the linker command to be for this?

**Comment by dipinhora** [comment]
@SeanTAllen adding `--link-ldcmd=bfd` to your `ponyc` command should make it link successfully (i think).

**Comment by SeanTAllen** [comment]
I need to clean up how the --link-ldcmd is done. It's a bit of a hack at the moment.

**Comment by SeanTAllen** [comment]
When this passes CI, I'm going to squash and merge.

**Pull request merged**
