### PR TITLE
Complete making version numbers in bintray user friendly

### PR DESCRIPTION
**Pull request by SeanTAllen**
So I can install version 0.1.1 instead of 0.1.1-some-hard-to-know-hash

### CODE REVIEW

**Review by mfelsche — APPROVED** [review]
@SeanTAllen would this limit us in rebuilding pony-stable packages? We'd need to issue another release right? 

I think this would be totally fine.

**Comment by SeanTAllen** [comment]
@mfelsche you are thinking rebuild to pick up pony runtime improvements, yes? if so, yes. new release would be needed

**Comment by mfelsche** [comment]
@SeanTAllen is this good to merge?

**Comment by SeanTAllen** [comment]
Pretty sure this should be closed.

@dipinhora should this be closed?

**Comment by dipinhora** [comment]
This is worth merging as long as `make deploy` exists in its current form. Once the new bintray deb packages for all debian/ubuntu distributions are confirmed to be working (should be easy to validate once I do a release now that I've gotten the ponyc release stuff in order) and all instructions updated to use the new bintray deb repo, we get to decide what to do with `make deploy`.

It's probably worth keeping around for folks who want to make packages locally but the "official" packages would be the ones built by Travis (for debs) and Fedora COPR (for rpms).

**Pull request merged**
